---
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - prek.toml
          - pyproject.toml
          - uv.lock

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - docs/**

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*.yaml
          - .github/workflows/*.yml

python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"

tests:
  - changed-files:
      - any-glob-to-any-file: tests/**

ha:automations:
  - changed-files:
      - any-glob-to-any-file: entities/automation/**/*.yaml

ha:binary-sensors:
  - changed-files:
      - any-glob-to-any-file:
          - entities/binary_sensor/**/*.yaml
          - entities/template/binary_sensor/**/*.yaml

ha:command-line:
  - changed-files:
      - any-glob-to-any-file: entities/command_line/**/*.yaml

ha:config:
  - changed-files:
      - any-glob-to-any-file:
          - configuration.yaml
          - customizations/**/*.yaml

ha:cover:
  - changed-files:
      - any-glob-to-any-file: entities/template/cover/**/*.yaml

ha:custom-components:
  - changed-files:
      - any-glob-to-any-file: custom_components/**

ha:custom-zha-quirks:
  - changed-files:
      - any-glob-to-any-file: custom_zha_quirks/**/*.py

ha:device-tracker:
  - changed-files:
      - any-glob-to-any-file: entities/device_tracker/**/*.yaml

ha:esphome:
  - changed-files:
      - any-glob-to-any-file:
          - .gitmodules
          - esphome
          - esphome/**/*.yaml

ha:input-boolean:
  - changed-files:
      - any-glob-to-any-file: entities/input_boolean/**/*.yaml

ha:input-button:
  - changed-files:
      - any-glob-to-any-file: entities/input_button/**/*.yaml

ha:input-datetime:
  - changed-files:
      - any-glob-to-any-file: entities/input_datetime/**/*.yaml

ha:input-number:
  - changed-files:
      - any-glob-to-any-file: entities/input_number/**/*.yaml

ha:input-select:
  - changed-files:
      - any-glob-to-any-file: entities/input_select/**/*.yaml

ha:input-text:
  - changed-files:
      - any-glob-to-any-file: entities/input_text/**/*.yaml

ha:integrations:
  - changed-files:
      - any-glob-to-any-file: integrations/**/*.yaml

ha:lovelace:
  - changed-files:
      - any-glob-to-any-file:
          - lovelace/**/*.yaml
          - lovelace/**/*.yml
          - lovelace.yaml
          - ui-lovelace.yaml

ha:media-player:
  - changed-files:
      - any-glob-to-any-file: entities/media_player/**/*.yaml

ha:mqtt:
  - changed-files:
      - any-glob-to-any-file: entities/mqtt/**/*.yaml

ha:rest:
  - changed-files:
      - any-glob-to-any-file: entities/rest/**/*.yaml

ha:rest-command:
  - changed-files:
      - any-glob-to-any-file: entities/rest_command/**/*.yaml

ha:scripts:
  - changed-files:
      - any-glob-to-any-file: entities/script/**/*.yaml

ha:sensors:
  - changed-files:
      - any-glob-to-any-file:
          - entities/command_line/sensor/**/*.yaml
          - entities/mqtt/sensor/**/*.yaml
          - entities/sensor/**/*.yaml
          - entities/template/sensor/**/*.yaml
          - entities/template_triggered/sensor/**/*.yaml

ha:shell-command:
  - changed-files:
      - any-glob-to-any-file:
          - entities/shell_command/**/*.yaml
          - resources/shell_command/**

ha:switch:
  - changed-files:
      - any-glob-to-any-file:
          - entities/mqtt/switch/**/*.yaml
          - entities/template/switch/**/*.yaml

ha:template:
  - changed-files:
      - any-glob-to-any-file: entities/template/**/*.yaml

ha:template-triggered:
  - changed-files:
      - any-glob-to-any-file: entities/template_triggered/**/*.yaml

ha:timer:
  - changed-files:
      - any-glob-to-any-file: entities/timer/**/*.yaml

ha:variables:
  - changed-files:
      - any-glob-to-any-file: entities/var/**/*.yaml
