[project]
name = "home-assistant"
version = "3.32.0"
description = ""
authors = [
  {name = "Will Garside", email = "worgarside@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
  "mcp-proxy>=0.8.0,<1.0.0",
]

[tool.basedpyright]
include = ["dev_tools"]
exclude = ["_local_sandbox"]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportMissingTypeStubs = "error"
reportUnnecessaryTypeIgnoreComment = "error"

[tool.codespell]
ignore-words-list = "hass,iif"
skip = '*.json,*.csv,*.xml,*.lock'

[tool.semantic_release]
tag_format = "{version}"
version_toml = ["pyproject.toml:project.version"]
commit_message = "chore(release): {version}"
major_on_zero = false
allow_zero_version = true
build_command = """
  python -m pip install uv
  uv lock
  git add uv.lock
"""

[tool.semantic_release.remote]
ignore_token_for_push = true

[tool.semantic_release.commit_parser_options]
allowed_tags = [
  "build",
  "chore",
  "ci",
  "deps",
  "docs",
  "feat",
  "fix",
  "hotfix",
  "perf",
  "refactor",
  "style",
  "test",
]
minor_tags = ["feat"]
patch_tags = ["build", "deps", "fix", "hotfix", "perf"]
parse_squash_commits = false

[tool.ruff]
fix = true
preview = true
line-length = 90
lint.select = ["ALL"]
lint.ignore = [
  "ANN401", # https://docs.astral.sh/ruff/rules/any-type/
  "D107",   # https://docs.astral.sh/ruff/rules/undocumented-public-init/
  "S314",   # https://docs.astral.sh/ruff/rules/suspicious-xml-element-tree-usage/
  "TRY003", # https://docs.astral.sh/ruff/rules/raise-vanilla-args/
  "ISC001", # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
  "TD002",  # https://docs.astral.sh/ruff/rules/missing-todo-author/
  "TD003",  # https://docs.astral.sh/ruff/rules/missing-todo-link/
  "EM",     # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em
  "FIX002", # https://docs.astral.sh/ruff/rules/line-contains-todo/
  "ANN101", # https://docs.astral.sh/ruff/rules/missing-type-self/
  "CPY",    # https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy
  "DOC201", # https://docs.astral.sh/ruff/rules/docstring-missing-returns/
  "DOC402", # https://docs.astral.sh/ruff/rules/docstring-missing-yields/
  "DOC501", # https://docs.astral.sh/ruff/rules/docstring-missing-exception/
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"dev_tools/**/*.py" = ["T201"]
"dev_tools/color_generator.py" = ["ERA001"]

[tool.ruff.lint.pycodestyle]
max-line-length = 115

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[dependency-groups]
dev = [
  "basedpyright>=1.39.9",
  "matplotlib>=3.10.3,<4.0.0",
  "prek>=0.4.12",
  "pyyaml>=6.0.2,<7.0.0",
]
