---
alias: /homeassistant/clear-service-reload-queue-on-start

id: homeassistant_clear_service_reload_queue_on_start

mode: single

max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start

variables:
  empty_pending: {}

  empty_in_flight: []

action:
  - action: var.set
    target:
      entity_id: var.auto_reload_queue
    data:
      value: 0
      attributes: >-
        {{
          {
            "pending": empty_pending | to_json,
            "in_flight": empty_in_flight | to_json,
          }
        }}
