---
resource_template: >-
  {%- set end = as_timestamp(now()) | int -%}
  {%- set start = end - 300 -%}
  http://10.0.0.125:5000/api/front_door/recordings?after={{ start }}&before={{ end }}

scan_interval: 60

timeout: 10

method: GET

sensor:
  - unique_id: frigate_front_door_recordings_last_5_minutes

    name: Frigate Front Door Recordings Last 5 Minutes

    value_template: "{{ value_json | count }}"

    unit_of_measurement: segments

    icon: mdi:video-check
