---
name: Auto-Create PR

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  create-pr:
    name: Create PR
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/__create-pull-request.yml@be008ae8f54348a000172e13598711c384dbc69b
    with:
      base-ref-name: ${{ github.event.repository.default_branch }}
      head-ref-name: ${{ github.ref_name }}
      pr-title: ${{ github.event.head_commit.message }}
      pr-draft: true
      update-pr-body-if-exists: true
    secrets: inherit
