---
name: Auto-Update PRs

on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: PR Auto-Update
    if: |
      (
        github.event_name == 'push' && github.ref == format(
          'refs/heads/{0}', github.event.repository.default_branch
        )
      ) ||
      (
        github.event_name == 'pull_request' &&
        github.event.label.name == 'bot:keep-updated'
      )
    # github-config-files has no releases; pin the latest audited main commit.
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/__pr_autoupdate.yml@be008ae8f54348a000172e13598711c384dbc69b
    secrets: inherit
